Remove /v1/services/:grid_name/:stack_name/:service_name/exec API
This was broken in two different ways:

1. Using @grid_service.containers.where(...) instead of .find_by()

NoMethodError (undefined method `host_node' for #<Mongoid::Criteria:0x0000000478b5c8>):
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/mongoid-4.0.2/lib/mongoid/criteria.rb:523:in `method_missing'
  /home/kontena/kontena/kontena/server/app/services/docker/container_executor.rb:28:in `host_node'
  /home/kontena/kontena/kontena/server/app/services/docker/container_executor.rb:34:in `client'
  /home/kontena/kontena/kontena/server/app/services/docker/container_executor.rb:14:in `exec_in_container'
  /home/kontena/kontena/kontena/server/app/routes/v1/services_api.rb:150:in `block (4 levels) in <class:ServicesApi>'

2. Relying on the old `$service-$instance` naming, which omits the stack prefix and results in HTTP 404 errors